Init
```{r}
library(coconatfly)
library(ggplot2) 
library(dplyr)
library(stringr)
library(bit64)
library(tidyr)
library(dbscan)
Sys.setenv(LANG = "eng")
```
Specify male_output_factor 
```{r}
male_output_factor = 2
```


Specify neurons of interest

```{r}
nois = c('AL-AST1' )#"MZ_lv2PN" ,'LHAD1g1'
neuron.fm <- NULL
neuron.meta <- NULL

for(noi in nois){
  neuron.fm.temp=cf_partner_summary(cf_ids(malecns = noi,flywire = noi), partners = 'out', aggregate.query = F)
  neuron.meta.temp=cf_meta(cf_ids(malecns = noi,flywire = noi))

  if(is.null(neuron.fm)){
    neuron.fm <- neuron.fm.temp
    neuron.meta <- neuron.meta.temp
  }
  else{
    neuron.fm <- bind_rows(neuron.fm,neuron.fm.temp)
    neuron.meta <- bind_rows(neuron.meta,neuron.meta.temp)
  }
}


```


function that can do multiple queries for metadata
```{r}
cf_meta_multi <- function(cell.ids,dataset) { # create a function with the name my_function
    meta <- NULL
    for(cell.id in cell.ids){
      if(dataset=='malecns'){
        meta.temp <-  tibble(cf_meta(cf_ids(malecns=cell.id)))
      }
      else if(dataset=='flywire'){
        meta.temp <-  tibble(cf_meta(cf_ids(flywire = cell.id)))
      }
      if(is.null(neuron.fm)){
        meta <- meta.temp
      }
      else{
        meta <- bind_rows(meta,meta.temp)
      }
    }
    return(meta)
}
```

Check the cells which have 0 weight in flywire if they maybe have a differnet name in flywire



```{r}
query.flywire<-neuron.fm.weights%>%
  filter(weight_flywire==0)%>%
  select(type.post)%>%
  pull()%>%
  cf_meta_multi(.,'malecns')%>%
  select(c(id,flywireType))



neuron.fm.corrected_names <- neuron.fm %>%
  left_join(query.flywire[c('id','flywireType')],by=c('type.post'='id'))%>%
  distinct()%>%
  mutate(type.post=if_else(type.post!=flywireType&!is.na(flywireType),flywireType,type.post))


```



```{r}
neuron.fm.weights<- neuron.fm.corrected_names%>%
  mutate(weight = if_else(dataset == "malecns", weight * male_output_factor, weight))%>%
  left_join(neuron.meta[c("key", "side")], by = c("query"="key"))  %>%
  group_by(query)%>%
  mutate(total_weight = sum(weight),
         weight_ratio = weight / total_weight)%>%
  ungroup()%>%
  filter(weight_ratio>0.01)%>%

  pivot_wider(id_cols = c(type.post,type.pre,side),names_from = dataset,values_from = c(weight_ratio,weight),values_fill=0)%>%
  mutate(sex_index_dif=weight_ratio_malecns-weight_ratio_flywire,
         sex_index_relative=(weight_ratio_malecns+weight_ratio_flywire)/(weight_ratio_malecns-weight_ratio_flywire),
         sex_index_exp=exp(weight_ratio_malecns)-exp(weight_ratio_flywire))%>%
  mutate(sex_index_dif_norm =(sex_index_dif - min(sex_index_dif)) / (max(sex_index_dif) - min(sex_index_dif)),
         sex_index_relative_norm =(sex_index_relative - min(sex_index_relative)) / (max(sex_index_relative) - min(sex_index_relative)),
         sex_index_exp_norm =(sex_index_exp - min(sex_index_exp)) / (max(sex_index_exp) - min(sex_index_exp)))%>%
  rowwise() %>%
  mutate(sex_index_avg = mean(c_across(c(sex_index_relative_norm, sex_index_dif_norm, sex_index_exp_norm)), na.rm = TRUE)) %>%
  ungroup()%>%
  mutate(sex_index_avg =(sex_index_avg - min(sex_index_avg)) / (max(sex_index_avg) - min(sex_index_avg)))%>%
  arrange(desc(sex_index_avg))



neuron.fm.weights
```



Function that checks if an ID exists in the flywire

```{r}
exists_flywire <- function(id_list){
  result_bool <- list()
  for(id in id_list){
    result <- cf_meta(cf_ids(flywire=id)) 
    
    if(is.null(result)){
      result_bool <- append(result_bool, FALSE) 
    }
    else{
      result_bool <- append(result_bool, TRUE) 
    }
  }
  return(result_bool)
}
```



```{r}
neuron.fm.weights.proc <- neuron.fm.weights%>% 
  group_by(type.post)%>%
  summarize(type_pre_values = str_c(type.pre, collapse = ", "),
            sex_index=mean(sex_index_avg),
            weight.abs.f=mean(weight_flywire),
            weight.abs.m=mean(weight_malecns),
            weight.ratio.f=round(mean(weight_ratio_flywire),2),
            weight.ratio.m=round(mean(weight_ratio_malecns),2),
            n=n())%>%
  #filter(weight.abs.f!=0)%>%
  #filter(weight.abs.m!=0)%>%
  filter(!is.na(type.post))%>%
  arrange(desc(sex_index))
neuron.fm.weights.proc

```


Clustering
```{r}
ast1.ds=cf_partners(cf_ids(malecns='AL-AST1', flywire = 'AL-AST1'), threshold = 10, partners = 'o')%>%
  filter(type %in% neuron.fm.weights.proc$type.post)


ast1.ds%>% filter(grepl("asc", class))%>% with(cf_cosine_plot(post_key,matrix=T)) ->a
ast1.ds%>% filter(grepl("desc", class))%>% with(cf_cosine_plot(post_key,matrix=T))->b
ast1.ds%>% filter(grepl("central", class))%>% with(cf_cosine_plot(post_key,matrix=T))->c
```

hdbscan
```{r}
cl_a <- hdbscan(a,4)
```
